import { packages as catalog } from "../packages";
import { company } from "../company";
import type { DemoState, Jamaah } from "./types";
import { createCostingSeed } from "./costing";

export const DEMO_TODAY = "2026-10-02";
export const documentNames = ["KTP", "KK", "Paspor", "Foto", "Vaksin", "Buku nikah", "Akta kelahiran", "Asuransi"];
const names = ["Ahmad Fauzi", "Siti Rahmawati", "Budi Santoso", "Rina Amelia", "Hendra Wijaya", "Dewi Lestari", "Muhammad Ridwan", "Nur Aisyah", "Agus Setiawan", "Sri Wahyuni", "Hasan Basri", "Fitri Handayani", "Dedi Kurniawan", "Yuni Astuti", "Abdul Rahman", "Lina Marlina", "Bambang Sutrisno", "Ratna Puspita", "Fajar Hidayat", "Nadia Putri", "Eko Prasetyo", "Reni Wulandari", "Arif Maulana", "Maya Sari", "Yusuf Iskandar", "Anisa Fadilah", "Taufik Hidayat", "Endah Permatasari", "Imam Susanto", "Lilis Suryani", "Rizky Ramadhan", "Farida Hanum", "Wahyu Saputra", "Sulastri Ningsih", "Joko Wibowo", "Nuri Safitri", "Darmawan Hakim", "Indah Pertiwi", "Dimas Pratama", "Aminah Zahra", "Rudi Hartono", "Hesti Utami", "Fahmi Abdullah", "Siska Damayanti", "Haris Nugroho", "Nurlaila Hasanah", "Ilham Akbar", "Novi Kurniasih"];
const cities = ["Jakarta", "Bandung", "Bekasi", "Surabaya", "Depok", "Tangerang"];

export function newJamaah(id: string, name: string, phone: string, gender: Jamaah["gender"] = "Laki-laki"): Jamaah {
  return { id, name, phone, gender, email: "", city: "Jakarta", address: "", nik: "", birthPlace: "", birthDate: "", marital: "Menikah", blood: "Belum diketahui", emergency: "", passport: "", passportOffice: "", passportIssue: "", passportExpiry: "", documents: Object.fromEntries(documentNames.map(n => [n, "Belum ada"])), visa: "Belum diajukan", visaNumber: "", visaSubmitted: "", visaApproved: "", visaExpiry: "", visaNotes: "", agentId: "", family: "", equipment: [], bus: "" };
}
export function createSeed(): DemoState {
  const packages = catalog.map(p => {
    const { departures, ...product } = p;
    return { ...product, status: departures.length ? "Terbit" as const : "Draft" as const };
  });
  const selected = [1, 10, 0, 2, 6, 4, 3, 5];
  const departures = selected.map((index, i) => {
    const p = catalog[index], d = p.departures[0];
    return { id: `UMR-${d.date.slice(2).replaceAll("-", "")}-${String.fromCharCode(65 + i)}`, packageId: p.id, date: d.date, capacity: i === 4 ? 25 : 45, airline: d.airline, flight: ["SV 817", "TK 57", "JT 110", "SV 823", "GA 980", "SV 819", "QR 957", "GA 982"][i], origin: "CGK", pnr: `HT${1026 + i}`, status: "Persiapan" as const, checks: { "Tiket pesawat": true, Hotel: true, Bus: i < 5, "Tour leader": true, Muthawwif: i < 6, Asuransi: true } };
  });
  const agents = ["Ahmad Hidayat", "Fitria Ramadhani", "H. Mansur Ali", "Nina Herlina", "Rizal Firmansyah", "Siti Khadijah", "Umar Faruq", "Yuliana Dewi", "Samsul Arifin", "Laila Fitria"].map((name, i) => ({ id: `AGT-${String(i + 1).padStart(3, "0")}`, name, phone: `08000000${String(i + 11).padStart(3, "0")}`, city: cities[i % 6], level: ["Coordinator", "Senior Agent", "Agent"][i % 3], commission: 1000000, status: i < 3 ? "Dibayar" as const : i < 6 ? "Disetujui" as const : "Menunggu" as const }));
  const jamaah = names.map((name, i) => ({ ...newJamaah(`JMH-${10281 + i}`, name, `08000000${100 + i}`, i % 2 ? "Perempuan" : "Laki-laki"), email: `${name.toLowerCase().replaceAll(" ", ".")}@example.com`, city: cities[i % 6], birthPlace: cities[(i + 1) % 6], passportOffice: cities[i % 6], visaSubmitted: "2026-09-20", visaApproved: i % 8 && i % 5 ? "2026-09-25" : "", visaExpiry: i % 8 && i % 5 ? "2026-12-25" : "", address: `Jl. Melati No. ${i + 12}, ${cities[i % 6]}`, nik: `DEMO-${10281 + i}`, birthDate: `${1968 + i % 28}-0${1 + i % 9}-${String(10 + i % 18)}`, emergency: `Keluarga ${name.split(" ")[0]} · 08000000000`, passport: i % 9 === 0 ? "" : `DEMO-A${1000000 + i}`, passportIssue: "2022-06-15", passportExpiry: i % 11 === 0 ? "2027-01-10" : "2032-06-15", documents: Object.fromEntries(documentNames.map((n, k) => [n, i % 9 === 0 && n === "Paspor" ? "Belum ada" : (i + k) % 13 === 0 ? "Diunggah" : (i + k) % 17 === 0 ? "Belum ada" : "Terverifikasi"])) as Jamaah["documents"], visa: i % 8 === 0 ? "Belum diajukan" as const : i % 5 === 0 ? "Diproses" as const : "Disetujui" as const, visaNumber: i % 8 && i % 5 ? `DEMO-V${24001 + i}` : "", agentId: agents[i % agents.length].id, family: i < 4 ? "Keluarga Fauzi" : "", equipment: i % 4 === 0 ? [] : ["Koper Besar", "Tas Paspor", "Seragam Batik"], bus: i < 12 ? "Bus 01" : "" }));
  const bookings = jamaah.map((j, i) => { const d = departures[i < 16 ? 0 : (i % 7) + 1]; const p = packages.find(p => p.id === d.packageId)!; return { id: `BK-${2026001 + i}`, jamaahId: j.id, departureId: d.id, roomType: "Quad" as const, total: p.price.quad, date: `2026-09-${String(1 + i % 28).padStart(2, "0")}`, due: "2026-10-05", status: "Aktif" as const }; });
  const payments = bookings.flatMap((b, i) => [
    { id: `PAY-${i + 1}-DP`, bookingId: b.id, amount: 10000000, date: b.date, method: "Transfer bank", status: "Terverifikasi" as const },
    ...(i % 4 === 0 ? [] : [{ id: `PAY-${i + 1}-02`, bookingId: b.id, amount: b.total - 10000000, date: i % 2 ? "2026-10-01" : "2026-09-28", method: "Transfer bank", status: i % 7 === 0 ? "Menunggu" as const : "Terverifikasi" as const }]),
  ]);
  const leads = ["Salman Al Farisi", "Zahra Aulia", "Hana Syafira", "Rizwan Hakim", "Putri Maharani", "Fikri Ramadhan", "Raisa Annisa", "Naufal Irfan", "Dian Kartika", "Iqbal Maulana", "Suci Ramadhani", "Faisal Akbar", "Dina Oktaviani", "Rafi Abdullah", "Nabila Azmi", "Benny Saputra", "Husna Karim", "Asep Saefullah", "Intan Safira", "Teguh Santoso", "Winda Apriliyani", "Farhan Zaki", "Meutia Azzahra", "Lukman Hakim"].map((name, i) => ({ id: `LD-${301 + i}`, name, phone: `08000000${200 + i}`, packageId: departures[i % 8].packageId, source: ["Website", "WhatsApp", "Instagram", "Referral", "Agen", "Walk-in", "Meta Ads"][i % 7], sales: ["Rina Amelia", "Dimas Pratama", "Nadia Putri"][i % 3], stage: (["Lead Baru", "Dihubungi", "Follow Up", "Qualified", "Lost"] as const)[i % 5], lastContact: "2026-10-01", followUp: "2026-10-03", notes: ["Tertarik keberangkatan bersama keluarga. Meminta rincian hotel dan jadwal manasik."] }));
  return {
    ...createCostingSeed(packages, departures),
    packages, departures, jamaah, bookings, payments, leads, agents,
    rooms: departures.flatMap(d => ["Makkah", "Madinah"].flatMap(hotel => Array.from({ length: 4 }, (_, i) => ({ id: `${d.id}-${hotel}-${i}`, departureId: d.id, hotel: hotel as "Makkah" | "Madinah", number: String(1201 + i), capacity: i < 2 ? 4 : i === 2 ? 3 : 2, gender: i % 2 ? "Perempuan" as const : "Laki-laki" as const, jamaahIds: bookings.filter(b => b.departureId === d.id).map(b => jamaah.find(j => j.id === b.jamaahId)!).filter(j => j.gender === (i % 2 ? "Perempuan" : "Laki-laki")).slice(i < 2 ? 0 : 3, i < 2 ? 3 : 4).map(j => j.id) })))),
    expenses: departures.flatMap((d, i) => ["Tiket pesawat", "Hotel", "Visa", "Transportasi", "Katering", "Pembimbing", "Handling", "Perlengkapan", "Marketing", "Lainnya"].map((category, k) => ({ id: `EXP-${i}-${k}`, departureId: d.id, category, vendor: [d.airline, "Al Haramain Hospitality", "Nusantara Visa Services", "Al Noor Transport"][k % 4], amount: [90000000, 45000000, 12000000, 8000000, 6500000, 4000000, 2000000, 4000000, 1500000, 1000000][k] * (i === 0 ? 1 : 0.25), date: "2026-09-28", status: k % 3 === 0 ? "Menunggu" as const : "Dibayar" as const }))),
    inventory: ["Koper Besar", "Koper Kabin", "Tas Paspor", "Kain Ihram", "Mukena", "Seragam Batik", "Buku Manasik", "ID Card", "Luggage Tag"].map((name, i) => ({ id: `ITM-${i + 1}`, name, stock: i === 6 ? 42 : 80 + i * 5, minimum: 25 })),
    manasik: ["Manasik #1", "Manasik #2", "Technical Meeting", "Verifikasi Dokumen", "Airport Briefing"].map((name, i) => ({ id: `EVT-${i + 1}`, name, date: `2026-10-0${3 + i}`, time: "09:00", location: i === 4 ? "Terminal 3 Soekarno-Hatta" : "Aula Hasta Travel, Jakarta", speaker: "Ust. Abdullah Karim", departureId: departures[0].id, attendees: i === 0 ? jamaah.slice(0, 12).map(j => j.id) : [] })),
    activities: [{ id: "ACT-1", date: "2026-10-02T09:42:00+07:00", user: "Rina Amelia", module: "Dokumen", action: "Mengunggah paspor Rina Amelia" }, { id: "ACT-2", date: "2026-10-02T09:15:00+07:00", user: "Finance", module: "Pembayaran", action: "Memverifikasi pelunasan Siti Rahmawati" }, { id: "ACT-3", date: "2026-10-01T16:30:00+07:00", user: "Operations", module: "Keberangkatan", action: "Mengonfirmasi alokasi hotel rombongan Oktober" }],
    notifications: [{ id: "N-1", category: "Dokumen", title: "Paspor membutuhkan perhatian", text: "Periksa kelengkapan dan masa berlaku sebelum keberangkatan.", href: "/admin/dokumen", read: false }, { id: "N-2", category: "Pembayaran", title: "Pembayaran menunggu verifikasi", text: "Cocokkan bukti transfer dengan invoice jamaah.", href: "/admin/pembayaran", read: false }, { id: "N-3", category: "Keberangkatan", title: "Persiapan rombongan Oktober", text: "Tinjau kesiapan manifest, kamar, dan manasik.", href: "/admin/keberangkatan", read: false }, { id: "N-4", category: "Inventory", title: "Periksa stok buku manasik", text: "Pastikan perlengkapan cukup untuk seluruh jamaah aktif.", href: "/admin/perlengkapan", read: true }, { id: "N-5", category: "Visa", title: "Status visa diperbarui", text: "Visa yang disetujui tersedia di pusat dokumen.", href: "/admin/dokumen", read: true }, { id: "N-6", category: "Sistem", title: "Selamat datang di Hasta Workspace", text: "Jelajahi alur operasional melalui akun demo.", href: "/admin/dashboard", read: true }],
    cms: [
      { id: "CMS-1", kind: "artikel", title: "Persiapan Umrah Pertama: Panduan untuk Keluarga", category: "Panduan", body: "Mulai persiapan dengan memeriksa masa berlaku paspor, memilih tanggal keberangkatan, dan mengikuti manasik. Tim Hasta membantu Anda melengkapi setiap kebutuhan sebelum berangkat.", status: "Terbit", date: "2026-09-25" },
      { id: "CMS-2", kind: "artikel", title: "Memilih Hotel yang Nyaman untuk Jamaah Lansia", category: "Tips Umrah", body: "Perhatikan jarak berjalan kaki dan akses tanpa tangga saat memilih hotel.", status: "Draft", date: "2026-10-01" },
      { id: "CMS-3", kind: "testimoni", title: "Siti Rahmawati · Bekasi", category: "Umrah Reguler", body: "Persiapannya jelas dan pembimbing sangat membantu. Kami sekeluarga bisa fokus beribadah.", status: "Terbit", date: "2026-09-20" },
      { id: "CMS-4", kind: "testimoni", title: "Hendra Wijaya · Jakarta", category: "Umrah Keluarga", body: "Informasi hotel dan jadwal disampaikan dengan rinci sejak awal.", status: "Draft", date: "2026-09-28" },
      { id: "CMS-5", kind: "galeri", title: "Masjidil Haram", category: "Perjalanan Umrah", body: "King Eliot · CC BY-SA 4.0; kredit lengkap di content/photos.ts.", status: "Terbit", date: "2026-09-20", image: "/foto/masjidil-haram.jpg" },
      { id: "CMS-6", kind: "galeri", title: "Masjid Nabawi", category: "Madinah", body: "Meshari Alawfi · CC BY 4.0; kredit lengkap di content/photos.ts.", status: "Terbit", date: "2026-09-20", image: "/foto/masjid-nabawi.jpg" },
    ],
    users: [{ id: "USR-1", name: "Ahmad", email: "demo@hasta.example", role: "Owner", active: true }, { id: "USR-2", name: "Rina Amelia", email: "rina@hasta.example", role: "Sales", active: true }, { id: "USR-3", name: "Fajar Hidayat", email: "fajar@hasta.example", role: "Finance", active: true }],
    permissions: { Owner: ["Dashboard", "Jamaah", "Pembayaran", "Pengeluaran", "Laporan", "Edit Paket", "Kelola User"], "Super Admin": ["Dashboard", "Jamaah", "Pembayaran", "Pengeluaran", "Laporan", "Edit Paket", "Kelola User"], Operations: ["Dashboard", "Jamaah", "Edit Paket"], Finance: ["Dashboard", "Jamaah", "Pembayaran", "Pengeluaran", "Laporan"], Sales: ["Dashboard", "Jamaah"], "Document Officer": ["Dashboard", "Jamaah"], "Tour Leader": ["Dashboard", "Jamaah"] },
    settings: { name: company.name, license: company.licensePPIU, address: company.address.street, phone: "08000000000", email: "info@hasta.example", website: "https://hasta-travel-umroh.vercel.app", branches: "Jakarta, Bandung, Surabaya", bank: company.bank.name, account: company.bank.accountNumber, color: "#f0a62b", notifications: "Aktif", documents: documentNames.join(", "), room: "Quad", duration: "9", session: "8 jam" }, broadcasts: [],
  };
}
