"use client";
import Image from "next/image";
import { useState } from "react";
import { Eye, Plus } from "lucide-react";
import { useDemo } from "./Store";
import { Badge, DataTable, Modal, PageHeader, Panel, SelectFilter } from "./ui";
import type { CmsEntry } from "@/content/admin/types";
import { dateLabel, uid } from "@/lib/admin/model";

export default function CMS({ kind }: { kind: CmsEntry["kind"] }) {
  const { state, transact } = useDemo();
  const [edit, setEdit] = useState<CmsEntry | "new" | null>(null);
  const [preview, setPreview] = useState<CmsEntry | null>(null);
  const [status, setStatus] = useState("");
  const rows = state.cms.filter(e => e.kind === kind && (!status || e.status === status));
  const toggle = (entry: CmsEntry) => transact(s => { s.cms.find(e => e.id === entry.id)!.status = entry.status === "Terbit" ? "Draft" : "Terbit"; }, `${entry.title}: ${entry.status === "Terbit" ? "disembunyikan" : "diterbitkan"} dalam pratinjau`, "Website");
  return <><PageHeader title={kind === "artikel" ? "Artikel" : kind === "testimoni" ? "Testimoni" : "Galeri"} description="Konten yang merawat kepercayaan calon jamaah." actions={<button className="admin-button primary" onClick={() => setEdit("new")}><Plus size={14} />Tambah {kind}</button>} /><p className="admin-notice" style={{ marginBottom: 20 }}>CMS demo: perubahan tersimpan selama sesi workspace, tidak diterbitkan ke website publik.</p>
    {kind === "galeri" ? <div className="package-grid">{rows.map(e => <Panel key={e.id}><div className="package-cover"><Image src={e.image || "/foto/masjidil-haram.jpg"} alt={e.title} fill sizes="(max-width: 760px) 100vw, 33vw" /></div><div className="package-content"><Badge>{e.status}</Badge><h2>{e.title}</h2><p>{e.category}</p><p>{e.body}</p><div className="admin-actions section-gap"><button className="admin-button" onClick={() => setEdit(e)}>Edit</button><button className="text-button" onClick={() => toggle(e)}>{e.status === "Terbit" ? "Sembunyikan" : "Tampilkan"}</button></div></div></Panel>)}</div> : <DataTable title={kind} rows={rows} filters={<SelectFilter label="Semua status" value={status} onChange={setStatus} options={["Terbit", "Draft"].map(v => ({ value: v, label: v }))} />} columns={[{ label: kind === "artikel" ? "Judul / slug" : "Nama jamaah", value: e => e.title, render: e => <button className="text-button" style={{ textAlign: "left" }} onClick={() => setEdit(e)}>{e.title}{kind === "artikel" && <small>{e.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/-$/, "")}</small>}</button> }, { label: "Kategori", value: e => e.category }, { label: "Status", value: e => e.status, render: e => <Badge>{e.status}</Badge> }, { label: "Tanggal", value: e => e.date, render: e => dateLabel(e.date) }, { label: "Aksi", value: e => e.status, render: e => <div className="admin-actions"><button className="icon-button" aria-label={`Pratinjau ${e.title}`} onClick={() => setPreview(e)}><Eye size={15} /></button><button className="text-button" onClick={() => toggle(e)}>{e.status === "Terbit" ? "Sembunyikan" : kind === "testimoni" ? "Setujui" : "Terbitkan"}</button></div> }]} />}
    {edit && <Modal title={`${edit === "new" ? "Tambah" : "Edit"} ${kind}`} onClose={() => setEdit(null)} wide><form className="admin-form" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); if (transact(s => { const entry: CmsEntry = { id: edit === "new" ? uid("CMS") : edit.id, kind, title: String(f.get("title")).trim(), category: String(f.get("category")), body: String(f.get("body")).trim(), status: String(f.get("status")) as CmsEntry["status"], date: String(f.get("date")), ...(kind === "galeri" ? { image: String(f.get("image")) } : {}) }; if (entry.title.length < 3 || !entry.body) throw new Error("Isi judul dan konten sebelum menyimpan."); if (edit === "new") s.cms.unshift(entry); else s.cms = s.cms.map(e => e.id === entry.id ? entry : e); }, `${kind} disimpan dalam pratinjau CMS`, "Website")) setEdit(null); }}><label>{kind === "testimoni" ? "Nama jamaah / kota" : "Judul"}<input name="title" required minLength={3} defaultValue={edit === "new" ? "" : edit.title} /></label><div className="form-grid"><label>Kategori<input name="category" required defaultValue={edit === "new" ? kind === "galeri" ? "Manasik" : "Panduan Umrah" : edit.category} /></label><label>Status<select name="status" defaultValue={edit === "new" ? "Draft" : edit.status}><option>Draft</option><option>Terbit</option></select></label></div>{kind === "galeri" && <label>Aset galeri<select name="image" defaultValue={edit === "new" ? "/foto/masjidil-haram.jpg" : edit.image}><option value="/foto/masjidil-haram.jpg">Masjidil Haram · King Eliot, CC BY-SA 4.0</option><option value="/foto/masjid-nabawi.jpg">Masjid Nabawi · Meshari Alawfi, CC BY 4.0</option><option value="/foto/abraj-al-bait.jpg">Abraj Al Bait · Ahmadrizo, CC BY-SA 4.0</option></select></label>}<label>{kind === "galeri" ? "Caption dan atribusi" : "Isi konten"}<textarea name="body" rows={6} required defaultValue={edit === "new" ? "" : edit.body} /></label><label>Tanggal<input name="date" type="date" required defaultValue={edit === "new" ? "2026-10-02" : edit.date} /></label><button className="admin-button primary">Simpan konten</button></form></Modal>}
    {preview && <Modal title="Pratinjau konten" onClose={() => setPreview(null)} wide><Badge>{preview.category}</Badge><h1 style={{ margin: "18px 0" }}>{preview.title}</h1><p className="muted">{dateLabel(preview.date)}</p><div style={{ whiteSpace: "pre-wrap", marginTop: 20 }}>{preview.body}</div></Modal>}
  </>;
}
