"use client";
import Link from "next/link";
import { useState } from "react";
import { Bell, CheckCheck, Eye, Send } from "lucide-react";
import { useDemo } from "./Store";
import { Badge, DataTable, Modal, PageHeader, Panel, SelectFilter, Tabs } from "./ui";
import { bookingFor, dateLabel, documentPercent, outstanding, paymentStatus, uid } from "@/lib/admin/model";
import { rupiah } from "@/lib/format";

const templates: Record<string, string> = {
  "Pengingat pembayaran": "Assalamu'alaikum Bapak/Ibu {nama}, mengingatkan bahwa sisa pembayaran paket {paket} sebesar {sisa} jatuh tempo pada {jatuhTempo}. Silakan hubungi tim Hasta Travel untuk konfirmasi.",
  "Kelengkapan dokumen": "Assalamu'alaikum Bapak/Ibu {nama}, mohon melengkapi dokumen perjalanan untuk paket {paket}. Tim kami siap membantu proses persiapannya.",
  "Jadwal manasik": "Assalamu'alaikum Bapak/Ibu {nama}, jadwal manasik paket {paket} telah tersedia. Silakan konfirmasi kehadiran kepada tim Hasta Travel.",
  "Informasi keberangkatan": "Assalamu'alaikum Bapak/Ibu {nama}, keberangkatan {paket} semakin dekat. Pastikan dokumen dan perlengkapan telah disiapkan. Sampai bertemu di titik kumpul.",
  "Visa disetujui": "Assalamu'alaikum Bapak/Ibu {nama}, visa perjalanan {paket} telah disetujui. Rincian dokumen dapat dikonfirmasi kepada tim kami.",
  "Konfirmasi booking": "Assalamu'alaikum Bapak/Ibu {nama}, pendaftaran paket {paket} telah kami catat. Terima kasih telah mempercayakan perjalanan ibadah kepada Hasta Travel.",
};
export default function Communication({ module }: { module: string }) {
  const { state, transact, notify } = useDemo();
  const [category, setCategory] = useState("");
  const [read, setRead] = useState("Semua");
  const [template, setTemplate] = useState("Pengingat pembayaran");
  const [message, setMessage] = useState(templates["Pengingat pembayaran"]);
  const [channel, setChannel] = useState("WhatsApp");
  const [filters, setFilters] = useState<Record<string, string>>({});
  const [preview, setPreview] = useState(false);
  if (module === "notifikasi") {
    const rows = state.notifications.filter(n => (!category || n.category === category) && (read === "Semua" || (read === "Belum dibaca" ? !n.read : n.read)));
    return <><PageHeader title="Pusat notifikasi" description="Jaga tim tetap mengetahui hal-hal yang membutuhkan perhatian." actions={<button className="admin-button" onClick={() => transact(s => { s.notifications.forEach(n => { n.read = true; }); }, "Semua notifikasi ditandai dibaca", "Notifikasi")}><CheckCheck size={15} />Tandai semua dibaca</button>} /><Tabs items={["Semua", "Belum dibaca", "Dibaca"]} value={read} onChange={setRead} /><div className="admin-actions" style={{ marginBottom: 20 }}><SelectFilter label="Semua kategori" value={category} onChange={setCategory} options={["Pembayaran", "Dokumen", "Visa", "Keberangkatan", "Inventory", "Sistem"].map(v => ({ value: v, label: v }))} /></div><Panel>{rows.map(n => <article className={`notification-row ${n.read ? "" : "unread"}`} key={n.id}><span className="alert-icon"><Bell size={18} /></span><div><b>{n.title}</b><p>{n.text}</p><Badge>{n.category}</Badge></div><Link className="text-button" href={n.href}>Tinjau →</Link><button className="icon-button" disabled={n.read} title="Tandai dibaca" aria-label={`Tandai ${n.title} dibaca`} onClick={() => transact(s => { s.notifications.find(p => p.id === n.id)!.read = true; }, "Notifikasi ditandai dibaca", "Notifikasi")}><CheckCheck size={18} /></button></article>)}{!rows.length && <p className="admin-empty">Tidak ada notifikasi pada pilihan ini.</p>}</Panel></>;
  }
  const audience = state.jamaah.filter(j => { const b = bookingFor(state, j.id); const d = state.departures.find(d => d.id === b?.departureId); return b && (!filters.package || d?.packageId === filters.package) && (!filters.departure || b.departureId === filters.departure) && (!filters.payment || paymentStatus(state, b) === filters.payment) && (!filters.documents || (filters.documents === "Lengkap" ? documentPercent(j) === 100 : documentPercent(j) < 100)) && (!filters.agent || j.agentId === filters.agent); });
  const j = audience[0]; const b = j ? bookingFor(state, j.id) : undefined;
  const text = message.replaceAll("{nama}", j?.name ?? "Nama jamaah").replaceAll("{paket}", state.packages.find(p => p.id === state.departures.find(d => d.id === b?.departureId)?.packageId)?.name ?? "paket umrah").replaceAll("{sisa}", b ? rupiah(outstanding(state, b)) : "Rp 0").replaceAll("{jatuhTempo}", b ? dateLabel(b.due) : "tanggal pada invoice");
  return <><PageHeader title="Broadcast" description="Komunikasi yang tepat, untuk jamaah yang tepat." actions={<span className="admin-badge amber">Simulasi pengiriman</span>} /><div className="dashboard-grid"><Panel title="Susun pesan"><div className="panel-body admin-form"><div className="form-grid"><label>Channel<select value={channel} onChange={e => setChannel(e.target.value)}><option>WhatsApp</option><option>Email</option></select></label><label>Template<select value={template} onChange={e => { setTemplate(e.target.value); setMessage(templates[e.target.value]); }}>{Object.keys(templates).map(k => <option key={k}>{k}</option>)}</select></label></div><label>Isi pesan<textarea value={message} onChange={e => setMessage(e.target.value)} rows={7} maxLength={3000} /></label><p className="muted" style={{ fontSize: 10 }}>Personalisasi: {"{nama}"}, {"{paket}"}, {"{sisa}"}, {"{jatuhTempo}"}</p><button className="admin-button primary" disabled={!audience.length || !message.trim()} onClick={() => setPreview(true)}><Eye size={15} />Pratinjau broadcast</button></div></Panel><Panel title="Penerima pesan" subtitle="Filter digabungkan untuk menentukan audiens"><div className="panel-body admin-form">{[
    { key: "package", label: "Semua paket", options: state.packages.map(p => ({ value: p.id, label: p.name })) }, { key: "departure", label: "Semua keberangkatan", options: state.departures.map(d => ({ value: d.id, label: d.id })) }, { key: "payment", label: "Status pembayaran", options: ["Lunas", "DP", "Cicilan", "Belum bayar"].map(v => ({ value: v, label: v })) }, { key: "documents", label: "Status dokumen", options: ["Lengkap", "Belum lengkap"].map(v => ({ value: v, label: v })) }, { key: "agent", label: "Semua agen", options: state.agents.map(a => ({ value: a.id, label: a.name })) },
  ].map(f => <SelectFilter key={f.key} label={f.label} value={filters[f.key] ?? ""} onChange={v => setFilters(old => ({ ...old, [f.key]: v }))} options={f.options} />)}<div className="admin-notice"><strong style={{ fontSize: 30 }}>{audience.length}</strong><br />estimasi penerima dari jamaah dengan booking aktif</div></div></Panel></div><Panel title="Riwayat simulasi"><DataTable title="broadcast" rows={state.broadcasts} columns={[{ label: "Pesan", value: b => b.title }, { label: "Channel", value: b => b.channel }, { label: "Penerima", value: b => b.recipients }, { label: "Tanggal", value: b => b.date, render: b => dateLabel(b.date) }, { label: "Status", value: () => "Simulasi selesai" }]} /></Panel>{preview && <Modal title="Pratinjau broadcast" onClose={() => setPreview(false)}><Badge>{channel} · Simulasi</Badge><p className="admin-notice section-gap" style={{ whiteSpace: "pre-wrap" }}>{text}</p><p className="muted section-gap">{audience.length} penerima: {audience.slice(0, 4).map(j => j.name).join(", ")}{audience.length > 4 ? ", …" : ""}</p><div className="modal-actions"><button className="admin-button primary" onClick={() => { const ok = transact(s => { s.broadcasts.unshift({ id: uid("BC"), title: template, recipients: audience.length, channel, date: "2026-10-02" }); }, `Simulasi broadcast ${channel} untuk ${audience.length} jamaah dicatat. Tidak ada pesan dikirim.`, "Broadcast"); if (ok) setPreview(false); else notify("Simulasi belum berhasil dicatat.", true); }}><Send size={14} />Simulasikan pengiriman</button></div></Modal>}</>;
}
