"use client";
import Link from "next/link";
import { useState } from "react";
import { Plus, Plane } from "lucide-react";
import { useDemo } from "./Store";
import { Badge, DataTable, Empty, Fields, Modal, PageHeader, Panel, Person, Progress, Stat, Confirm } from "./ui";
import { dateLabel, members, readiness, uid } from "@/lib/admin/model";

export default function Departures({ id }: { id?: string }) {
  const { state, transact } = useDemo();
  const [create, setCreate] = useState(false);
  const [advance, setAdvance] = useState(false);
  const d = state.departures.find(d => d.id === id);
  if (id && !d) return <Empty title="Keberangkatan tidak ditemukan" />;
  if (d) {
    const ready = readiness(state, d.id);
    const people = members(state, d.id);
    return <><Link href="/admin/keberangkatan" className="text-button">← Semua keberangkatan</Link><PageHeader title={d.id} description={`${state.packages.find(p => p.id === d.packageId)?.name} · ${dateLabel(d.date)}`} actions={<><Badge>{d.status}</Badge><Link className="admin-button primary" href={`/admin/manifest?departure=${d.id}`}>Lihat manifest</Link></>} /><div className="dashboard-grid"><Panel title="Kesiapan keberangkatan" subtitle="Dihitung dari data jamaah dan checklist tim"><div className="panel-body"><strong style={{ fontSize: 56, fontWeight: 650 }}>{ready.percent}<span style={{ fontSize: 22 }}>%</span></strong><p className="muted">kesiapan operasional</p><div className="two-columns section-gap">{Object.entries(ready.checks).map(([k, v]) => <Progress key={k} value={v} label={k} />)}</div></div></Panel><Panel title="Informasi rombongan"><Fields data={{ "Tanggal berangkat": dateLabel(d.date), "Jamaah / kapasitas": `${people.length} / ${d.capacity}`, Penerbangan: `${d.airline} · ${d.flight}`, PNR: d.pnr, "Tour leader": "Fajar Hidayat", Muthawwif: "Ust. Abdullah Karim" }} /><div className="panel-body admin-actions"><Link className="admin-button" href={`/admin/rooming?departure=${d.id}`}>Atur kamar</Link>{d.status !== "Selesai" && <button className="admin-button primary" onClick={() => setAdvance(true)}>{d.status === "Persiapan" ? "Tandai berangkat" : "Selesaikan perjalanan"}</button>}</div></Panel></div><Panel title="Checklist tim operasional" subtitle="Item ini dikonfirmasi manual oleh tim"><div className="panel-body two-columns">{Object.entries(d.checks).map(([k, v]) => <label className="checklist-row" key={k}><input type="checkbox" checked={v} onChange={e => transact(s => { s.departures.find(p => p.id === d.id)!.checks[k] = e.target.checked; }, `${k} ${d.id} diperbarui`, "Keberangkatan")} /><span>{k}</span><Badge>{v ? "Siap" : "Menunggu"}</Badge></label>)}</div></Panel><div className="section-gap"><DataTable title="jamaah rombongan" rows={people} columns={[{ label: "Jamaah", value: j => j.name, render: j => <Person name={j.name} sub={j.id} href={`/admin/jamaah/${j.id}`} /> }, { label: "Paspor", value: j => j.passport || "Belum diisi" }, { label: "Visa", value: j => j.visa, render: j => <Badge>{j.visa}</Badge> }, { label: "Bus", value: j => j.bus || "Belum dialokasikan" }]} /></div>{advance && <Confirm title="Perbarui status perjalanan?" text={d.status === "Persiapan" ? `Kesiapan saat ini ${ready.percent}%. Status berangkat hanya bisa dicatat setelah kesiapan 100%.` : "Rombongan akan ditandai selesai. Seluruh riwayat tetap tersedia."} onClose={() => setAdvance(false)} onConfirm={() => transact(s => { const batch = s.departures.find(p => p.id === d.id)!; if (batch.status === "Persiapan" && readiness(s, d.id).percent < 100) throw new Error("Lengkapi seluruh persiapan sebelum menandai berangkat."); batch.status = batch.status === "Persiapan" ? "Berangkat" : "Selesai"; }, `Status perjalanan ${d.id} diperbarui`, "Keberangkatan")} />}</>;
  }
  return <><PageHeader title="Keberangkatan" description="Dari produk perjalanan menjadi rombongan yang siap berangkat." actions={<button className="admin-button primary" onClick={() => setCreate(true)}><Plus size={15} />Buat keberangkatan</button>} /><div className="admin-stats"><Stat label="Total keberangkatan" value={state.departures.length} detail="Batch operasional" icon={<Plane />} /><Stat label="Dalam persiapan" value={state.departures.filter(d => d.status === "Persiapan").length} detail="Pantau checklist persiapan" /><Stat label="Sedang berjalan" value={state.departures.filter(d => d.status === "Berangkat").length} detail="Rombongan di perjalanan" /><Stat label="Selesai" value={state.departures.filter(d => d.status === "Selesai").length} detail="Perjalanan ditutup" /></div><DataTable title="keberangkatan" rows={state.departures} columns={[{ label: "Kode keberangkatan", value: d => d.id, render: d => <Link className="text-button" href={`/admin/keberangkatan/${d.id}`}>{d.id}<small>{dateLabel(d.date)}</small></Link> }, { label: "Paket", value: d => state.packages.find(p => p.id === d.packageId)?.name ?? "" }, { label: "Flight", value: d => `${d.airline} ${d.flight}` }, { label: "Kapasitas", value: d => `${members(state, d.id).length} / ${d.capacity}` }, { label: "Kesiapan", value: d => readiness(state, d.id).percent, render: d => <Progress value={readiness(state, d.id).percent} label={`${readiness(state, d.id).percent}%`} /> }, { label: "Status", value: d => d.status, render: d => <Badge>{d.status}</Badge> }, { label: "Manifest", value: d => d.id, render: d => <Link className="text-button" href={`/admin/manifest?departure=${d.id}`}>Buka →</Link> }]} />
    {create && <Modal title="Buat keberangkatan" onClose={() => setCreate(false)}><form className="admin-form" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); if (transact(s => { s.departures.unshift({ id: uid("UMR"), packageId: String(f.get("package")), date: String(f.get("date")), capacity: Number(f.get("capacity")), airline: String(f.get("airline")), flight: String(f.get("flight")), origin: "CGK", pnr: "Belum diterbitkan", status: "Persiapan", checks: { "Tiket pesawat": false, Hotel: false, Bus: false, "Tour leader": false, Muthawwif: false, Asuransi: false } }); }, "Keberangkatan baru dibuat", "Keberangkatan")) setCreate(false); }}><label>Paket<select name="package">{state.packages.filter(p => p.status === "Terbit").map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><div className="form-grid"><label>Tanggal<input name="date" type="date" required min="2026-10-02" /></label><label>Kapasitas<input name="capacity" type="number" min={1} max={500} defaultValue={45} required /></label></div><label>Maskapai<input name="airline" defaultValue="Saudia" required /></label><label>Nomor penerbangan<input name="flight" required placeholder="SV 817" /></label><button className="admin-button primary">Simpan keberangkatan</button></form></Modal>}
  </>;
}
