"use client";
import { useState } from "react";
import { useSearchParams } from "next/navigation";
import { Download, FileCheck2, Check, X } from "lucide-react";
import { useDemo } from "./Store";
import { Badge, DataTable, Modal, PageHeader, Person, SelectFilter, Stat, Tabs } from "./ui";
import { DocumentChecklist, VisaPanel } from "./Jamaah";
import { bookingFor, dateLabel, documentPercent, manifestReady, members, outstanding, validPassport } from "@/lib/admin/model";
import { exportExcel, printTable } from "@/lib/admin/export";
import type { Jamaah } from "@/content/admin/types";

export default function Documents({ manifest = false }: { manifest?: boolean }) {
  const { state, transact, notify } = useDemo();
  const params = useSearchParams();
  const [departure, setDeparture] = useState(params.get("departure") || (manifest ? state.departures[0].id : ""));
  const [tab, setTab] = useState("Semua dokumen");
  const [filter, setFilter] = useState("");
  const [selection, setSelection] = useState<string[]>([]);
  const [detail, setDetail] = useState<string | null>(null);
  const [sisko, setSisko] = useState(false);
  const people = departure ? members(state, departure) : state.jamaah;
  const d = state.departures.find(d => d.id === departure);
  const packageName = d ? state.packages.find(p => p.id === d.packageId)?.name : "";
  const room = (j: Jamaah) => state.rooms.find(r => r.hotel === "Makkah" && r.departureId === departure && r.jamaahIds.includes(j.id))?.number ?? "—";
  const rows = people.filter(j => !filter || (manifest ? (filter === "Siap" ? manifestReady(state, j, departure) : !manifestReady(state, j, departure)) : tab === "Visa" ? j.visa === filter : tab === "Semua dokumen" ? (filter === "Lengkap" ? documentPercent(j) === 100 : documentPercent(j) < 100) : j.documents[tab] === filter));
  const header = ["No", "Nama", "Paspor", "Jenis kelamin", "Tanggal lahir", "Paket", "Kamar", "Visa", "Flight", "Status"];
  const exportRows = (people: Jamaah[]) => people.map((j, i) => [i + 1, j.name, j.passport, j.gender, dateLabel(j.birthDate), packageName ?? "", room(j), j.visa, d?.flight ?? "", manifestReady(state, j, departure) ? "Siap" : "Perlu dilengkapi"]);
  const readyCount = d ? people.filter(j => manifestReady(state, j, d.id)).length : 0;
  const expiryCount = people.filter(j => { const b = bookingFor(state, j.id); const departure = state.departures.find(d => d.id === b?.departureId); return !validPassport(j, departure?.date ?? "2026-10-02"); }).length;
  return <><PageHeader title={manifest ? "Manifest jamaah" : "Dokumen & Visa"} description={manifest ? "Rincian rombongan yang rapi, lengkap, dan siap diekspor." : "Pantau kelengkapan, verifikasi dokumen, dan proses visa dari satu tempat."} actions={manifest && <button className="admin-button primary" onClick={() => setSisko(true)}><FileCheck2 size={15} />Persiapan SISKOPATUH</button>} />
    <div className="admin-stats"><Stat label={manifest ? "Jamaah rombongan" : "Dokumen lengkap"} value={manifest ? people.length : people.filter(j => documentPercent(j) === 100).length} detail={manifest ? `${d?.capacity ?? 0} kapasitas kursi` : "Seluruh dokumen terverifikasi"} /><Stat label={manifest ? "Siap ekspor" : "Belum lengkap"} value={manifest ? readyCount : people.filter(j => documentPercent(j) < 100).length} detail={manifest ? "Identitas, dokumen, visa, pembayaran" : "Perlu tindak lanjut tim"} /><Stat label="Perlu verifikasi" value={people.filter(j => Object.values(j.documents).includes("Diunggah")).length} detail="Jamaah dengan unggahan baru" /><Stat label="Paspor perlu ditinjau" value={expiryCount} detail="Kosong / masa berlaku singkat" /></div>
    {!manifest && <Tabs items={["Semua dokumen", "Paspor", "Visa", "KTP", "Vaksin", "Foto"]} value={tab} onChange={v => { setTab(v); setFilter(""); setSelection([]); }} />}
    {selection.length > 0 && !manifest && <div className="admin-actions" style={{ marginBottom: 15 }}><button className="admin-button primary" onClick={() => transact(s => { let count = 0; s.jamaah.filter(j => selection.includes(j.id)).forEach(j => { if (tab === "Visa") { if (j.documents.Paspor !== "Terverifikasi" || !j.passport) throw new Error(`Paspor ${j.name} belum terverifikasi. Batch tidak diubah.`); j.visa = "Diproses"; count++; } else Object.keys(j.documents).filter(k => (tab === "Semua dokumen" || k === tab) && j.documents[k] === "Diunggah").forEach(k => { j.documents[k] = "Terverifikasi"; count++; }); }); if (!count) throw new Error("Tidak ada unggahan baru yang dapat diverifikasi pada pilihan ini."); }, tab === "Visa" ? "Visa pilihan diproses (simulasi)" : "Dokumen pilihan diverifikasi", "Dokumen")}>{tab === "Visa" ? "Proses visa pilihan" : "Verifikasi unggahan pilihan"}</button><button className="admin-button" onClick={() => notify(`Simulasi permintaan pembaruan dokumen untuk ${selection.length} jamaah. Tidak ada pesan dikirim.`)}>Minta pembaruan (simulasi)</button></div>}
    <DataTable title={manifest ? "manifest" : "dokumen jamaah"} rows={rows} selection={selection} onSelection={setSelection} filters={<><SelectFilter label={manifest ? "Pilih keberangkatan" : "Semua keberangkatan"} value={departure} onChange={v => { setDeparture(v || (manifest ? state.departures[0].id : "")); setSelection([]); }} options={state.departures.map(d => ({ value: d.id, label: `${d.id} · ${dateLabel(d.date)}` }))} /><SelectFilter label="Semua status" value={filter} onChange={v => { setFilter(v); setSelection([]); }} options={(manifest ? ["Siap", "Perlu dilengkapi"] : tab === "Visa" ? ["Belum diajukan", "Diajukan", "Diproses", "Disetujui", "Ditolak"] : tab === "Semua dokumen" ? ["Lengkap", "Belum lengkap"] : ["Belum ada", "Diunggah", "Terverifikasi", "Ditolak"]).map(v => ({ value: v, label: v }))} /></>} actions={manifest ? (rows => <button className="admin-button" onClick={() => { if (!printTable(`Manifest ${departure}`, header, exportRows(rows), [`${packageName} · ${dateLabel(d?.date ?? "")}`])) notify("Izinkan popup untuk mencetak manifest.", true); }}><Download size={14} />Cetak / PDF</button>) : undefined} columns={manifest ? [
      { label: "Jamaah", value: j => j.name, render: j => <Person name={j.name} sub={j.id} href={`/admin/jamaah/${j.id}`} /> }, { label: "Paspor", value: j => j.passport || "Belum ada" }, { label: "L/P", value: j => j.gender }, { label: "Tanggal lahir", value: j => j.birthDate, render: j => dateLabel(j.birthDate) }, { label: "Paket", value: () => packageName ?? "" }, { label: "Kamar", value: room }, { label: "Visa", value: j => j.visa, render: j => <Badge>{j.visa}</Badge> }, { label: "Flight", value: () => d?.flight ?? "" }, { label: "Status", value: j => manifestReady(state, j, departure) ? "Siap" : "Perlu dilengkapi", render: j => <Badge>{manifestReady(state, j, departure) ? "Siap" : "Perlu dilengkapi"}</Badge> },
    ] : [
      { label: "Jamaah", value: j => j.name, render: j => <Person name={j.name} sub={j.id} href={`/admin/jamaah/${j.id}`} /> }, { label: "Paspor", value: j => j.passport || "Belum ada" }, { label: "Kelengkapan", value: j => documentPercent(j), render: j => <Badge>{documentPercent(j) === 100 ? "Terverifikasi" : `${documentPercent(j)}% lengkap`}</Badge> }, { label: tab === "Semua dokumen" ? "Visa" : tab, value: j => tab === "Visa" || tab === "Semua dokumen" ? j.visa : j.documents[tab], render: j => <Badge>{tab === "Visa" || tab === "Semua dokumen" ? j.visa : j.documents[tab]}</Badge> }, { label: "Berlaku hingga", value: j => j.passportExpiry, render: j => dateLabel(j.passportExpiry) }, { label: "Aksi", value: j => j.id, render: j => <button className="admin-button" onClick={() => setDetail(j.id)}>Tinjau {tab === "Visa" ? "visa" : "dokumen"}</button> },
    ]} />
    {detail && <Modal title={state.jamaah.find(j => j.id === detail)?.name ?? "Dokumen"} onClose={() => setDetail(null)} wide>{tab === "Visa" ? <VisaPanel key={detail} jamaahId={detail} /> : <DocumentChecklist jamaahId={detail} />}</Modal>}
    {sisko && d && <Modal title="Persiapan Data SISKOPATUH" onClose={() => setSisko(false)}><p className="admin-notice">Format data siap ekspor · simulasi. Tidak terhubung ke API pemerintah dan tidak mengirim data ke SISKOPATUH.</p><h3 style={{ margin: "20px 0" }}>{readyCount} / {people.length} jamaah siap</h3>{[
      ["Identitas jamaah", people.filter(j => j.nik && j.birthDate).length], ["Paspor", people.filter(j => validPassport(j, d.date) && j.documents.Paspor === "Terverifikasi").length], ["Pembayaran", people.filter(j => { const b = bookingFor(state, j.id); return b && outstanding(state, b) === 0; }).length], ["Asuransi", people.filter(j => j.documents.Asuransi === "Terverifikasi").length], ["Visa", people.filter(j => j.visa === "Disetujui").length], ["Tiket", d.checks["Tiket pesawat"] ? people.length : 0],
    ].map(([label, count]) => <div className="checklist-row" key={label}>{count === people.length ? <Check size={17} className="green-text" /> : <X size={17} className="red-text" />}<span>{label}</span><b>{count} / {people.length}</b></div>)}<p className="admin-notice warning section-gap">{people.length - readyCount} jamaah membutuhkan perbaikan data. Format demo perlu dipetakan ulang ke format resmi sebelum penggunaan produksi.</p><div className="modal-actions"><button className="admin-button primary" onClick={() => { exportExcel(`persiapan-siskopatuh-${d.id}`, header, exportRows(people)); notify("Berkas persiapan diekspor. Tidak ada pengiriman ke pemerintah."); }}>Ekspor data persiapan</button></div></Modal>}
  </>;
}
