"use client";
import Link from "next/link";
import { useState } from "react";
import { Plus, Download, Send, Wallet, CircleCheck, Receipt, Clock3 } from "lucide-react";
import { useDemo } from "./Store";
import { Badge, Confirm, DataTable, Empty, Fields, PageHeader, Panel, Person, SelectFilter, Stat, Tabs } from "./ui";
import { CreateForm, type CreateKind } from "./CreateForm";
import { dateLabel, outstanding, paid, paymentStatus, verifyPayment } from "@/lib/admin/model";
import { printTable, downloadText } from "@/lib/admin/export";
import { rupiah, rupiahSingkat } from "@/lib/format";

export default function Finance({ module, id }: { module: string; id?: string }) {
  const { state, transact, notify } = useDemo();
  const [create, setCreate] = useState<CreateKind | null>(null);
  const [status, setStatus] = useState("");
  const [departure, setDeparture] = useState("");
  const [tab, setTab] = useState("Invoice jamaah");
  const [cancel, setCancel] = useState(false);
  const booking = state.bookings.find(b => b.id === id);
  const person = (id: string) => state.jamaah.find(j => j.id === id)!;
  const packageName = (departureId: string) => state.packages.find(p => p.id === state.departures.find(d => d.id === departureId)?.packageId)?.name ?? "";
  const printInvoice = (id: string) => { const b = state.bookings.find(b => b.id === id)!; if (!printTable(`Invoice INV/${b.id}`, ["Deskripsi", "Jumlah", "Total"], [[packageName(b.departureId), 1, rupiah(b.total)], ["Terbayar", "", rupiah(paid(state, b.id))], ["Sisa tagihan", "", rupiah(outstanding(state, b))]], [person(b.jamaahId).name, `Jatuh tempo ${dateLabel(b.due)}`, `Bank: ${state.settings.bank} · ${state.settings.account} (demo)`])) notify("Izinkan popup browser untuk mencetak invoice.", true); };
  if (id && !booking) return <Empty title="Booking / invoice tidak ditemukan" />;
  if (booking) {
    const j = person(booking.jamaahId);
    const payments = state.payments.filter(p => p.bookingId === booking.id);
    return <><PageHeader title={module === "booking" ? `Booking ${booking.id}` : `INV/${booking.id}`} description={`${j.name} · ${packageName(booking.departureId)}`} actions={<><button className="admin-button" onClick={() => printInvoice(booking.id)}><Download size={14} />Cetak / PDF</button><button className="admin-button primary" disabled={booking.status === "Batal" || outstanding(state, booking) === 0} onClick={() => setCreate("Pembayaran")}><Plus size={14} />Catat pembayaran</button></>} /><div className="invoice-sheet"><div className="flex-between"><div><span className="eyebrow" style={{ color: "#758255" }}>HASTA TRAVEL</span><h1 style={{ marginTop: 8 }}>INVOICE</h1><p className="muted">INV/{booking.id}</p></div><Badge>{paymentStatus(state, booking)}</Badge></div><Fields data={{ "Ditagihkan kepada": <Person name={j.name} sub={j.phone} href={`/admin/jamaah/${j.id}`} />, "Tanggal booking": dateLabel(booking.date), Keberangkatan: <Link className="text-button" href={`/admin/keberangkatan/${booking.departureId}`}>{booking.departureId}</Link>, "Jatuh tempo": dateLabel(booking.due), "Tipe kamar": booking.roomType, Status: booking.status }} /><div className="table-scroll"><table><thead><tr><th>Deskripsi</th><th>Jumlah</th><th>Total</th></tr></thead><tbody><tr><td>{packageName(booking.departureId)}<small>Paket {booking.roomType} · 1 jamaah</small></td><td>1</td><td>{rupiah(booking.total)}</td></tr></tbody></table></div><div className="invoice-total"><p>Terbayar: {rupiah(paid(state, booking.id))}</p><p className="muted">Sisa tagihan</p><strong>{rupiah(outstanding(state, booking))}</strong></div><p className="admin-notice section-gap">Rekening simulasi: {state.settings.bank} · {state.settings.account}. Tidak menerima transfer dana.</p></div>
      <div className="section-gap"><Panel title="Riwayat pembayaran" action={<button className="text-button" onClick={() => notify(`Simulasi pengingat pembayaran untuk ${j.name} disiapkan. Tidak ada pesan dikirim.`)}><Send size={13} style={{ display: "inline" }} /> Simulasi pengingat</button>}><DataTable title="transaksi" rows={payments} columns={[{ label: "Referensi", value: p => p.id }, { label: "Tanggal", value: p => p.date, render: p => dateLabel(p.date) }, { label: "Metode", value: p => p.method }, { label: "Nominal", value: p => p.amount, render: p => rupiah(p.amount) }, { label: "Status", value: p => p.status, render: p => <Badge>{p.status}</Badge> }, { label: "Aksi", value: p => p.status, render: p => p.status === "Menunggu" ? <button className="admin-button" onClick={() => transact(s => verifyPayment(s, p.id), `Pembayaran ${p.id} ${j.name} terverifikasi`, "Pembayaran")}>Verifikasi</button> : p.status === "Terverifikasi" ? <button className="text-button" onClick={() => downloadText(`kuitansi-${p.id}.txt`, `HASTA TRAVEL — KUITANSI DEMO\n${p.id}\nDiterima dari: ${j.name}\nInvoice: INV/${booking.id}\nNominal: ${rupiah(p.amount)}\nTanggal: ${dateLabel(p.date)}\nMetode: ${p.method}\nData simulasi, bukan bukti pembayaran riil.`)}>Unduh kuitansi</button> : "—" }]} /></Panel></div><div className="admin-actions section-gap"><Link className="admin-button" href={`/admin/jamaah/${j.id}`}>Lengkapi data jamaah →</Link>{booking.status === "Aktif" && <button className="text-button" onClick={() => setCancel(true)}>Batalkan booking</button>}</div>
      {cancel && <Confirm title="Batalkan booking?" text="Booking akan dibatalkan, kursi dan alokasi kamar dilepas. Pembayaran dicatat sebagai dikembalikan dalam simulasi; tidak ada transfer dana riil." onClose={() => setCancel(false)} onConfirm={() => transact(s => { s.bookings.find(b => b.id === booking.id)!.status = "Batal"; s.payments.filter(p => p.bookingId === booking.id).forEach(p => { p.status = "Dikembalikan"; }); s.rooms.filter(r => r.departureId === booking.departureId).forEach(r => { r.jamaahIds = r.jamaahIds.filter(id => id !== j.id); }); const lead = s.leads.find(l => l.bookingId === booking.id); if (lead) lead.stage = "Lost"; }, `Booking ${booking.id} ${j.name} dibatalkan (simulasi refund)`, "Booking")} />}
      {create && <CreateForm kind={create} bookingId={booking.id} onClose={() => setCreate(null)} />}
    </>;
  }
  if (module === "pengeluaran") {
    const bookings = state.bookings.filter(b => b.status === "Aktif" && (!departure || b.departureId === departure));
    const expenses = state.expenses.filter(e => !departure || e.departureId === departure);
    const revenue = bookings.reduce((n, b) => n + b.total, 0), cost = expenses.reduce((n, e) => n + e.amount, 0);
    return <><PageHeader title="Pengeluaran" description="Kendalikan biaya perjalanan dan pantau estimasi profit setiap rombongan." actions={<button className="admin-button primary" onClick={() => setCreate("Pengeluaran")}><Plus size={15} />Tambah pengeluaran</button>} /><div className="admin-stats"><Stat label="Nilai booking" value={rupiahSingkat(revenue)} detail="Booking aktif" /><Stat label="Biaya operasional" value={rupiahSingkat(cost)} detail="Termasuk biaya belum dibayar" /><Stat label="Estimasi laba kotor" value={rupiahSingkat(revenue - cost)} detail="Bukan laporan akuntansi final" /><Stat label="Estimasi margin" value={`${revenue ? ((revenue - cost) / revenue * 100).toFixed(1) : 0}%`} detail="Laba kotor / nilai booking" /></div><DataTable title="pengeluaran" rows={expenses} filters={<SelectFilter label="Semua keberangkatan" value={departure} onChange={setDeparture} options={state.departures.map(d => ({ value: d.id, label: d.id }))} />} columns={[{ label: "Referensi", value: e => e.id }, { label: "Keberangkatan", value: e => e.departureId }, { label: "Kategori", value: e => e.category }, { label: "Vendor", value: e => e.vendor }, { label: "Nominal", value: e => e.amount, render: e => rupiah(e.amount) }, { label: "Status", value: e => e.status, render: e => <Badge>{e.status}</Badge> }, { label: "Aksi", value: e => e.status, render: e => e.status === "Menunggu" ? <button className="text-button" onClick={() => transact(s => { s.expenses.find(p => p.id === e.id)!.status = "Dibayar"; }, `Pengeluaran ${e.id} ditandai dibayar (simulasi)`, "Pengeluaran")}>Tandai dibayar</button> : "Tercatat" }]} />{create && <CreateForm kind={create} onClose={() => setCreate(null)} />}</>;
  }
  const active = state.bookings.filter(b => b.status === "Aktif");
  const rows = state.bookings.filter(b => (!status || paymentStatus(state, b) === status) && (!departure || b.departureId === departure));
  const total = active.reduce((n, b) => n + b.total, 0), collected = active.reduce((n, b) => n + paid(state, b.id), 0);
  const title = module === "booking" ? "Booking" : module === "invoice" ? "Invoice" : "Pembayaran";
  return <><PageHeader title={title} description={module === "booking" ? "Setiap pendaftaran terhubung langsung ke jamaah, invoice, dan keberangkatan." : "Pencatatan yang rapi, pembayaran yang mudah dipantau."} actions={<button className="admin-button primary" onClick={() => setCreate(module === "pembayaran" ? "Pembayaran" : "Booking")}><Plus size={15} />{module === "pembayaran" ? "Catat pembayaran" : module === "invoice" ? "Buat invoice / booking" : "Tambah booking"}</button>} /><div className="admin-stats"><Stat label="Nilai booking aktif" value={rupiahSingkat(total)} detail={`${active.length} invoice aktif`} icon={<Receipt />} /><Stat label="Terkumpul" value={rupiahSingkat(collected)} detail="Dana terverifikasi" icon={<CircleCheck />} /><Stat label="Belum lunas" value={rupiahSingkat(total - collected)} detail={`${active.filter(b => outstanding(state, b) > 0).length} invoice`} icon={<Wallet />} /><Stat label="Menunggu verifikasi" value={state.payments.filter(p => p.status === "Menunggu").length} detail={`Refund simulasi: ${rupiahSingkat(state.payments.filter(p => p.status === "Dikembalikan").reduce((n, p) => n + p.amount, 0))}`} icon={<Clock3 />} /></div>
    {module === "pembayaran" && <Tabs items={["Invoice jamaah", "Verifikasi pembayaran"]} value={tab} onChange={setTab} />}
    {module === "pembayaran" && tab === "Verifikasi pembayaran" ? <DataTable title="transaksi" rows={state.payments.filter(p => !status || p.status === status)} filters={<SelectFilter label="Semua status transaksi" value={status} onChange={setStatus} options={["Menunggu", "Terverifikasi", "Dikembalikan"].map(v => ({ value: v, label: v }))} />} columns={[{ label: "Referensi", value: p => p.id }, { label: "Jamaah", value: p => { const b = state.bookings.find(b => b.id === p.bookingId)!; return person(b.jamaahId).name; } }, { label: "Invoice", value: p => p.bookingId, render: p => <Link href={`/admin/invoice/${p.bookingId}`} className="text-button">INV/{p.bookingId}</Link> }, { label: "Nominal", value: p => p.amount, render: p => rupiah(p.amount) }, { label: "Status", value: p => p.status, render: p => <Badge>{p.status}</Badge> }, { label: "Aksi", value: p => p.status, render: p => p.status === "Menunggu" ? <button className="admin-button" onClick={() => transact(s => verifyPayment(s, p.id), `Pembayaran ${p.id} terverifikasi`, "Pembayaran")}>Verifikasi</button> : "Selesai" }]} /> : <DataTable title={title.toLowerCase()} rows={rows} filters={<><SelectFilter label="Semua status" value={status} onChange={setStatus} options={["Lunas", "DP", "Cicilan", "Belum bayar", "Jatuh tempo", "Batal"].map(v => ({ value: v, label: v }))} /><SelectFilter label="Semua keberangkatan" value={departure} onChange={setDeparture} options={state.departures.map(d => ({ value: d.id, label: d.id }))} /></>} columns={[
      { label: module === "booking" ? "Booking" : "Invoice", value: b => b.id, render: b => <Link className="text-button" href={`/admin/${module === "booking" ? "booking" : "invoice"}/${b.id}`}>{module === "booking" ? b.id : `INV/${b.id}`}</Link> },
      { label: "Jamaah", value: b => person(b.jamaahId).name, render: b => <Person name={person(b.jamaahId).name} sub={person(b.jamaahId).id} href={`/admin/jamaah/${b.jamaahId}`} /> },
      { label: "Paket", value: b => packageName(b.departureId), render: b => <>{packageName(b.departureId)}<small>{b.departureId}</small></> },
      { label: "Total", value: b => b.total, render: b => rupiah(b.total) }, { label: "Terbayar", value: b => paid(state, b.id), render: b => rupiah(paid(state, b.id)) }, { label: "Sisa", value: b => outstanding(state, b), render: b => <b>{rupiah(outstanding(state, b))}</b> },
      { label: "Jatuh tempo", value: b => b.due, render: b => dateLabel(b.due) }, { label: "Status", value: b => paymentStatus(state, b), render: b => <Badge>{paymentStatus(state, b)}</Badge> },
    ]} />}{create && <CreateForm kind={create} onClose={() => setCreate(null)} />}
  </>;
}
