"use client";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, Plus, Copy, CalendarDays, Plane, MapPin, Pencil } from "lucide-react";
import type { AdminPackage } from "@/content/admin/types";
import { dateLabel, members, paid, uid } from "@/lib/admin/model";
import { rupiah, rupiahSingkat } from "@/lib/format";
import { useDemo } from "./Store";
import { Badge, Confirm, DataTable, Empty, Fields, Modal, PageHeader, Panel, Person, SelectFilter, Tabs } from "./ui";
import { CreateForm } from "./CreateForm";

export default function Packages({ id, website = false }: { id?: string; website?: boolean }) {
  const { state, transact } = useDemo();
  const [create, setCreate] = useState(false);
  const [edit, setEdit] = useState(false);
  const [archive, setArchive] = useState(false);
  const [tab, setTab] = useState("Overview");
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("");
  const p = state.packages.find(p => p.id === id);
  const update = (p: AdminPackage, status: AdminPackage["status"]) => transact(s => { s.packages.find(k => k.id === p.id)!.status = status; }, `Paket ${p.name}: ${status}`, "Paket");
  if (id && !p) return <Empty title="Paket tidak ditemukan" />;
  if (p) {
    const departures = state.departures.filter(d => d.packageId === p.id);
    const bookings = state.bookings.filter(b => departures.some(d => d.id === b.departureId) && b.status === "Aktif");
    const people = state.jamaah.filter(j => bookings.some(b => b.jamaahId === j.id));
    return <><Link className="text-button" href="/admin/paket"><ArrowLeft size={13} style={{ display: "inline" }} /> Semua paket</Link><PageHeader title={p.name} description={`${p.id.toUpperCase()} · ${p.duration} hari · ${p.type.replaceAll("-", " ")}`} actions={<><Badge>{p.status}</Badge><button className="admin-button" onClick={() => setEdit(true)}><Pencil size={14} />Edit paket</button></>} /><Tabs items={["Overview", "Itinerary", "Harga", "Hotel", "Penerbangan", "Jamaah", "Dokumen", "Finance"]} value={tab} onChange={setTab} />
      {tab === "Overview" && <div className="two-columns"><Panel title="Ringkasan produk"><Fields data={{ "Durasi perjalanan": `${p.duration} hari`, "Harga mulai": rupiah(p.price.quad), "Keberangkatan operasional": departures.length, "Jamaah terdaftar": people.length, Status: <Badge>{p.status}</Badge>, "Sisa kursi operasional": departures.reduce((n, d) => n + d.capacity - members(state, d.id).length, 0) }} /><div className="panel-body admin-actions"><button className="admin-button" onClick={() => transact(s => { const id = uid("PKT"); s.packages.unshift({ ...structuredClone(p), id, slug: id.toLowerCase(), name: `${p.name} — Salinan`, status: "Draft", featured: false }); }, "Salinan paket dibuat sebagai draft", "Paket")}><Copy size={14} />Duplikat</button><button className="admin-button primary" onClick={() => update(p, p.status === "Terbit" ? "Draft" : "Terbit")}>{p.status === "Terbit" ? "Batalkan publikasi" : "Terbitkan"}</button><button className="admin-button" onClick={() => update(p, "Ditutup")}>Tutup pendaftaran</button><button className="text-button" onClick={() => setArchive(true)}>Arsipkan</button></div></Panel><Panel title="Fasilitas perjalanan"><div className="panel-body stack">{p.facilities.map(f => <p key={f} style={{ fontSize: 12 }}>✓ {f}</p>)}</div></Panel></div>}
      {tab === "Itinerary" && <Panel title="Rencana perjalanan"><div className="panel-body">{p.itinerary.map(i => <div className="checklist-row" key={i.day}><span className="admin-avatar">{i.day}</span><div><b>{i.title}</b><p className="muted" style={{ fontSize: 12 }}>{i.description}</p></div></div>)}</div></Panel>}
      {tab === "Harga" && <><div className="three-columns">{(["quad", "triple", "double"] as const).map(room => <Panel key={room} title={room.toUpperCase()}><div className="panel-body"><strong style={{ fontSize: 27 }}>{rupiah(p.price[room])}</strong><p className="muted">Per jamaah dewasa · termasuk fasilitas paket</p></div></Panel>)}</div><p className="admin-notice section-gap">Anak menggunakan tempat tidur: harga sesuai tipe kamar. Bayi tanpa tempat tidur: penawaran terpisah setelah konfirmasi maskapai.</p></>}
      {tab === "Hotel" && <div className="two-columns">{[["Makkah", p.makkahHotel], ["Madinah", p.madinahHotel]].map(([city, hotel]) => { const h = hotel as typeof p.makkahHotel; return <Panel key={String(city)} title={String(city)}><Fields data={{ Hotel: h.name, Kategori: `${h.starRating} bintang`, "Jarak berjalan": `${h.distanceMeters} meter`, Akses: h.stepFree ? "Bebas tangga" : "Perlu perhatian mobilitas" }} /></Panel>; })}</div>}
      {tab === "Penerbangan" && <DataTable title="penerbangan" rows={departures} columns={[{ label: "Keberangkatan", value: d => d.id, render: d => <Link className="text-button" href={`/admin/keberangkatan/${d.id}`}>{d.id}</Link> }, { label: "Tanggal", value: d => d.date, render: d => dateLabel(d.date) }, { label: "Maskapai", value: d => d.airline }, { label: "Penerbangan", value: d => d.flight }, { label: "PNR", value: d => d.pnr }, { label: "Kursi", value: d => `${members(state, d.id).length} / ${d.capacity}` }]} />}
      {tab === "Jamaah" && <DataTable title="jamaah" rows={people} columns={[{ label: "Nama", value: j => j.name, render: j => <Person name={j.name} sub={j.id} href={`/admin/jamaah/${j.id}`} /> }, { label: "Telepon", value: j => j.phone }, { label: "Visa", value: j => j.visa, render: j => <Badge>{j.visa}</Badge> }]} />}
      {tab === "Dokumen" && <Panel title="Persyaratan paket"><div className="panel-body stack">{p.requirements.map(r => <p key={r}>• {r}</p>)}<Link href="/admin/dokumen" className="text-button">Periksa dokumen jamaah →</Link></div></Panel>}
      {tab === "Finance" && <Panel title="Ringkasan keuangan paket"><Fields data={{ "Nilai booking": rupiah(bookings.reduce((n, b) => n + b.total, 0)), "Dana terverifikasi": rupiah(bookings.reduce((n, b) => n + paid(state, b.id), 0)), "Estimasi biaya operasional": rupiah(state.expenses.filter(e => departures.some(d => d.id === e.departureId)).reduce((n, e) => n + e.amount, 0)) }} /><div className="panel-body"><Link className="text-button" href="/admin/pengeluaran">Lihat estimasi profit per keberangkatan →</Link></div></Panel>}
      {archive && <Confirm title="Arsipkan paket?" text="Paket tidak lagi menerima booking baru. Booking yang sudah ada tetap tersimpan." onClose={() => setArchive(false)} onConfirm={() => update(p, "Arsip")} />}
      {edit && <Modal title="Edit paket" onClose={() => setEdit(false)}><form className="admin-form" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); if (transact(s => { const k = s.packages.find(k => k.id === p.id)!; k.name = String(f.get("name")).trim(); k.duration = Number(f.get("duration")); for (const r of ["quad", "triple", "double"] as const) k.price[r] = Number(f.get(r)); if (k.name.length < 3 || Object.values(k.price).some(v => !Number.isSafeInteger(v) || v <= 0)) throw new Error("Nama dan harga paket tidak valid."); }, `${p.name} diperbarui; harga booking lama tetap`, "Paket")) setEdit(false); }}><label>Nama paket<input name="name" required minLength={3} defaultValue={p.name} /></label><label>Durasi<input type="number" name="duration" min={1} max={60} required defaultValue={p.duration} /></label>{(["quad", "triple", "double"] as const).map(r => <label key={r}>Harga {r} (Rp)<input type="number" min={1} step={1} required name={r} defaultValue={p.price[r]} /></label>)}<button className="admin-button primary">Simpan paket</button></form></Modal>}
    </>;
  }
  const rows = state.packages.filter(p => (!status || p.status === status) && p.name.toLowerCase().includes(query.toLowerCase()));
  return <><PageHeader title={website ? "Paket website" : "Paket Umrah"} description={website ? "Kelola etalase perjalanan, publikasi, dan paket unggulan." : "Produk perjalanan yang dirancang dengan perhatian pada setiap detail."} actions={<button className="admin-button primary" onClick={() => setCreate(true)}><Plus size={15} />Buat paket</button>} />{website && <p className="admin-notice" style={{ marginBottom: 20 }}>Pratinjau pengelolaan CMS. Perubahan publikasi di workspace ini merupakan simulasi dan tidak mengubah website publik.</p>}<div className="table-toolbar" style={{ background: "white", border: "1px solid var(--a-line)", borderRadius: 8, marginBottom: 22 }}><input aria-label="Cari paket" value={query} onChange={e => setQuery(e.target.value)} placeholder="Cari nama paket…" /><SelectFilter label="Semua status" value={status} onChange={setStatus} options={["Terbit", "Draft", "Ditutup", "Arsip"].map(v => ({ value: v, label: v }))} /><span className="muted">{rows.length} paket</span></div>
    <div className="package-grid">{rows.map((p, i) => { const ds = state.departures.filter(d => d.packageId === p.id); const booked = ds.reduce((n, d) => n + members(state, d.id).length, 0), capacity = ds.reduce((n, d) => n + d.capacity, 0); return <article className="admin-panel" key={p.id}><div className="package-cover"><Image src={i % 2 ? "/foto/masjid-nabawi.jpg" : "/foto/masjidil-haram.jpg"} alt={i % 2 ? "Masjid Nabawi" : "Masjidil Haram"} fill sizes="(max-width: 760px) 100vw, 33vw" /><Badge>{p.status}</Badge></div><div className="package-content"><small className="muted">{p.id.toUpperCase()} · {p.type.replaceAll("-", " ")}</small><Link href={`/admin/paket/${p.id}`}><h2>{p.name}</h2></Link><div className="package-meta"><span><CalendarDays size={12} />{p.duration} hari</span><span><Plane size={12} />{ds[0]?.airline ?? "Belum dijadwalkan"}</span></div><p><MapPin size={12} style={{ display: "inline" }} /> {p.makkahHotel.name}</p><div className="flex-between" style={{ margin: "16px 0" }}><span><small className="muted">Mulai dari</small><br /><strong>{rupiahSingkat(p.price.quad)}</strong></span><span className="muted" style={{ fontSize: 10 }}>{booked} / {capacity} kursi<br />{capacity - booked} tersedia</span></div>{website ? <div className="admin-actions"><button className="admin-button" onClick={() => update(p, p.status === "Terbit" ? "Draft" : "Terbit")}>{p.status === "Terbit" ? "Unpublish" : "Publish"}</button><button className="admin-button" aria-pressed={p.featured} onClick={() => transact(s => { s.packages.find(k => k.id === p.id)!.featured = !p.featured; }, `Status unggulan ${p.name} diperbarui`, "Website")}>{p.featured ? "★ Unggulan" : "Jadikan unggulan"}</button><Link className="text-button" href={`/admin/paket/${p.id}`}>Edit →</Link></div> : <Link href={`/admin/paket/${p.id}`} className="admin-button" style={{ width: "100%" }}>Kelola paket →</Link>}</div></article>; })}</div>{!rows.length && <Empty />}<p className="muted" style={{ marginTop: 18, fontSize: 9 }}>Foto: King Eliot, CC BY-SA 4.0 · Meshari Alawfi, CC BY 4.0. <Link href="/" className="text-button">Kredit lengkap di website publik.</Link></p>{create && <CreateForm kind="Paket" onClose={() => setCreate(false)} />}
  </>;
}
