"use client";
import Link from "next/link";
import { useState } from "react";
import { Plus } from "lucide-react";
import { useDemo } from "./Store";
import { Badge, DataTable, Empty, Fields, Modal, PageHeader, Panel, Person, Stat, Tabs } from "./ui";
import { rupiah, rupiahSingkat } from "@/lib/format";
import { dateLabel, uid } from "@/lib/admin/model";

export default function Partners({ module, id }: { module: string; id?: string }) {
  const { state, transact } = useDemo();
  const [create, setCreate] = useState(false);
  const [tab, setTab] = useState("Profil");
  const [vendor, setVendor] = useState<string | null>(null);
  const agent = state.agents.find(a => a.id === id);
  const agentBookings = (id: string) => state.bookings.filter(b => b.status === "Aktif" && state.jamaah.find(j => j.id === b.jamaahId)?.agentId === id);
  const commission = (id: string) => agentBookings(id).length * (state.agents.find(a => a.id === id)?.commission ?? 0);
  const approve = (id: string) => transact(s => { const a = s.agents.find(a => a.id === id)!; a.status = a.status === "Menunggu" ? "Disetujui" : "Dibayar"; }, `Komisi ${state.agents.find(a => a.id === id)?.name} diperbarui (simulasi)`, "Komisi");
  if (id && !agent) return <Empty title="Agen tidak ditemukan" />;
  if (agent) return <><PageHeader title={agent.name} description={`${agent.id} · ${agent.level} · ${agent.city}`} /><Tabs items={["Profil", "Jamaah", "Booking", "Komisi", "Pembayaran", "Aktivitas"]} value={tab} onChange={setTab} />{tab === "Profil" && <Panel title="Profil mitra"><Fields data={{ Nama: agent.name, ID: agent.id, Telepon: agent.phone, Kota: agent.city, Level: agent.level, "Komisi per jamaah": rupiah(agent.commission) }} /></Panel>}{tab === "Jamaah" && <DataTable title="jamaah agen" rows={state.jamaah.filter(j => j.agentId === agent.id)} columns={[{ label: "Jamaah", value: j => j.name, render: j => <Person name={j.name} sub={j.id} href={`/admin/jamaah/${j.id}`} /> }, { label: "Telepon", value: j => j.phone }, { label: "Kota", value: j => j.city }]} />}{tab === "Booking" && <DataTable title="booking agen" rows={agentBookings(agent.id)} columns={[{ label: "Booking", value: b => b.id, render: b => <Link className="text-button" href={`/admin/booking/${b.id}`}>{b.id}</Link> }, { label: "Keberangkatan", value: b => b.departureId }, { label: "Nilai", value: b => b.total, render: b => rupiah(b.total) }]} />}{["Komisi", "Pembayaran"].includes(tab) && <Panel title="Komisi mitra"><Fields data={{ "Booking aktif": agentBookings(agent.id).length, "Tarif per jamaah": rupiah(agent.commission), "Total komisi": rupiah(commission(agent.id)), Status: <Badge>{agent.status}</Badge> }} /><div className="panel-body">{agent.status !== "Dibayar" && <button className="admin-button primary" onClick={() => approve(agent.id)}>{agent.status === "Menunggu" ? "Setujui komisi" : "Tandai dibayar (simulasi)"}</button>}<p className="admin-notice section-gap">Komisi dihitung dari booking aktif. Pembayaran pada showcase tidak mengirim dana.</p></div></Panel>}{tab === "Aktivitas" && <DataTable title="aktivitas agen" rows={state.activities.filter(a => a.action.includes(agent.name))} columns={[{ label: "Tanggal", value: a => a.date, render: a => dateLabel(a.date) }, { label: "Aktivitas", value: a => a.action }]} />}</>;
  if (module === "vendor") {
    const vendors = [...new Set(state.expenses.map(e => e.vendor))].map(name => ({ id: name, name, categories: [...new Set(state.expenses.filter(e => e.vendor === name).map(e => e.category))].join(", "), total: state.expenses.filter(e => e.vendor === name).reduce((n, e) => n + e.amount, 0), paid: state.expenses.filter(e => e.vendor === name && e.status === "Dibayar").reduce((n, e) => n + e.amount, 0) }));
    return <><PageHeader title="Supplier / Vendor" description="Mitra layanan dan seluruh biaya operasional yang terhubung dengannya." /><DataTable title="vendor" rows={vendors} columns={[{ label: "Mitra layanan", value: v => v.name, render: v => <button className="text-button" onClick={() => setVendor(v.name)}>{v.name}</button> }, { label: "Kategori", value: v => v.categories }, { label: "Nilai transaksi", value: v => v.total, render: v => rupiah(v.total) }, { label: "Sudah dibayar", value: v => v.paid, render: v => rupiah(v.paid) }, { label: "Sisa", value: v => v.total - v.paid, render: v => rupiah(v.total - v.paid) }]} /><p className="admin-notice section-gap">Vendor baru otomatis muncul saat dicatat pada pengeluaran. <Link className="text-button" href="/admin/pengeluaran">Tambah pengeluaran →</Link></p>{vendor && <Modal title={vendor} onClose={() => setVendor(null)} wide><DataTable title="transaksi vendor" rows={state.expenses.filter(e => e.vendor === vendor)} columns={[{ label: "Keberangkatan", value: e => e.departureId }, { label: "Kategori", value: e => e.category }, { label: "Nominal", value: e => e.amount, render: e => rupiah(e.amount) }, { label: "Status", value: e => e.status, render: e => <Badge>{e.status}</Badge> }]} /></Modal>}</>;
  }
  return <><PageHeader title={module === "komisi" ? "Komisi agen" : "Agen & reseller"} description="Tumbuh bersama mitra. Setiap jamaah, penjualan, dan komisi tercatat." actions={<button className="admin-button primary" onClick={() => setCreate(true)}><Plus size={14} />Tambah agen</button>} /><div className="admin-stats"><Stat label="Mitra terdaftar" value={state.agents.length} detail="Jaringan agen Hasta" /><Stat label="Komisi menunggu" value={rupiahSingkat(state.agents.filter(a => a.status === "Menunggu").reduce((n, a) => n + commission(a.id), 0))} detail="Perlu persetujuan" /><Stat label="Disetujui" value={rupiahSingkat(state.agents.filter(a => a.status === "Disetujui").reduce((n, a) => n + commission(a.id), 0))} detail="Siap dibayarkan" /><Stat label="Dibayar" value={rupiahSingkat(state.agents.filter(a => a.status === "Dibayar").reduce((n, a) => n + commission(a.id), 0))} detail="Pembayaran simulasi" /></div><DataTable title="agen" rows={state.agents} columns={[{ label: "Agen", value: a => a.name, render: a => <Person name={a.name} sub={a.id} href={`/admin/agen/${a.id}`} /> }, { label: "Kota / level", value: a => `${a.city} ${a.level}`, render: a => <>{a.city}<small>{a.level}</small></> }, { label: "Telepon", value: a => a.phone }, { label: "Booking aktif", value: a => agentBookings(a.id).length }, { label: "Penjualan", value: a => agentBookings(a.id).reduce((n, b) => n + b.total, 0), render: a => rupiah(agentBookings(a.id).reduce((n, b) => n + b.total, 0)) }, { label: "Komisi", value: a => commission(a.id), render: a => rupiah(commission(a.id)) }, { label: "Status", value: a => a.status, render: a => <Badge>{a.status}</Badge> }, { label: "Aksi", value: a => a.status, render: a => a.status === "Dibayar" ? "Tercatat" : <button className="text-button" onClick={() => approve(a.id)}>{a.status === "Menunggu" ? "Setujui" : "Tandai dibayar"}</button> }]} />{create && <Modal title="Tambah agen" onClose={() => setCreate(false)}><form className="admin-form" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); if (transact(s => { s.agents.push({ id: uid("AGT"), name: String(f.get("name")).trim(), phone: String(f.get("phone")), city: String(f.get("city")), level: String(f.get("level")), commission: Number(f.get("commission")), status: "Menunggu" }); }, "Agen baru ditambahkan", "Agen")) setCreate(false); }}><label>Nama<input name="name" required minLength={3} /></label><label>Telepon<input name="phone" type="tel" required pattern="[+0-9\s\-]{8,18}" /></label><label>Kota<input name="city" required /></label><label>Level<select name="level"><option>Agent</option><option>Senior Agent</option><option>Coordinator</option></select></label><label>Komisi per jamaah (Rp)<input name="commission" type="number" required min={0} step={1} defaultValue={1000000} /></label><button className="admin-button primary">Simpan agen</button></form></Modal>}</>;
}
