"use client";
import { useState } from "react";
import { useSearchParams } from "next/navigation";
import { BedDouble, Plus, WandSparkles, X } from "lucide-react";
import { useDemo } from "./Store";
import { Badge, Modal, PageHeader, Panel, Person, SelectFilter, Stat } from "./ui";
import { assignRoom, autoAssign, members, uid } from "@/lib/admin/model";
import type { Room } from "@/content/admin/types";

export default function Rooming() {
  const { state, transact } = useDemo();
  const params = useSearchParams();
  const [departure, setDeparture] = useState(params.get("departure") || state.departures[0].id);
  const [hotel, setHotel] = useState<Room["hotel"]>("Makkah");
  const [create, setCreate] = useState(false);
  const [assign, setAssign] = useState<string | null>(null);
  const rooms = state.rooms.filter(r => r.departureId === departure && r.hotel === hotel);
  const people = members(state, departure);
  const unassigned = people.filter(j => !rooms.some(r => r.jamaahIds.includes(j.id)));
  const p = state.packages.find(p => p.id === state.departures.find(d => d.id === departure)?.packageId);
  const separated = [...new Set(people.map(j => j.family).filter(Boolean))].filter(f => new Set(rooms.filter(r => r.jamaahIds.some(id => people.find(j => j.id === id)?.family === f)).map(r => r.id)).size > 1);
  return <><PageHeader title="Rooming list" description="Kamar yang tertata, perjalanan yang lebih nyaman." actions={<><button className="admin-button" onClick={() => setCreate(true)}><Plus size={14} />Tambah kamar</button><button className="admin-button primary" onClick={() => transact(s => autoAssign(s, departure, hotel), "Alokasi otomatis selesai; periksa jamaah yang belum mendapat kamar", "Rooming")}><WandSparkles size={14} />Auto Assign</button></>} /><div className="admin-actions" style={{ marginBottom: 20 }}><SelectFilter label="Pilih keberangkatan" value={departure} onChange={v => setDeparture(v || state.departures[0].id)} options={state.departures.map(d => ({ value: d.id, label: d.id }))} /><select aria-label="Kota hotel" value={hotel} onChange={e => setHotel(e.target.value as Room["hotel"])}><option>Makkah</option><option>Madinah</option></select><span className="muted">{hotel === "Makkah" ? p?.makkahHotel.name : p?.madinahHotel.name}</span></div><div className="admin-stats"><Stat label="Kamar tersedia" value={rooms.length} detail={hotel} icon={<BedDouble />} /><Stat label="Sudah dialokasikan" value={people.length - unassigned.length} detail={`${people.length} jamaah dalam rombongan`} /><Stat label="Belum mendapat kamar" value={unassigned.length} detail="Pilih jamaah, lalu tentukan kamar" /><Stat label="Sisa tempat tidur" value={rooms.reduce((n, r) => n + r.capacity - r.jamaahIds.length, 0)} detail="Sesuai kapasitas kamar" /></div>
    {separated.length > 0 && <p className="admin-notice warning" style={{ marginBottom: 20 }}>Keluarga berada di kamar berbeda: {separated.join(", ")}. Tinjau kebutuhan keluarga; alokasi otomatis tetap memisahkan jenis kelamin.</p>}
    <div className="dashboard-grid"><div className="room-grid" style={{ gridTemplateColumns: "repeat(auto-fit,minmax(235px,1fr))" }}>{rooms.map(r => <article className="room-card" key={r.id} onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); const id = e.dataTransfer.getData("text/plain"); transact(s => assignRoom(s, id, r.id), `Jamaah dialokasikan ke kamar ${r.number}`, "Rooming"); }}><div className="flex-between"><h3>Kamar {r.number}</h3><BedDouble size={18} className="muted" /></div><div className="flex-between" style={{ marginTop: 8 }}><Badge>{r.capacity === 4 ? "QUAD" : r.capacity === 3 ? "TRIPLE" : "DOUBLE"}</Badge><small className="muted">{r.jamaahIds.length} / {r.capacity} · {r.gender === "Laki-laki" ? "Laki-laki" : "Perempuan"}</small></div><div className="room-slots">{Array.from({ length: Math.max(r.capacity, r.jamaahIds.length) }, (_, i) => { const j = people.find(j => j.id === r.jamaahIds[i]); return j ? <div className="room-slot filled" draggable onDragStart={e => e.dataTransfer.setData("text/plain", j.id)} key={j.id}><button className="text-button" onClick={() => setAssign(j.id)} style={{ margin: 0, textAlign: "left" }}>{j.name}</button><button aria-label={`Lepas ${j.name} dari kamar ${r.number}`} title="Lepas dari kamar" onClick={() => transact(s => { const room = s.rooms.find(k => k.id === r.id)!; room.jamaahIds = room.jamaahIds.filter(id => id !== j.id); }, `${j.name} dilepas dari kamar ${r.number}`, "Rooming")}><X size={13} /></button></div> : <div className="room-slot" key={i}><Plus size={13} />Tempat tidur tersedia</div>; })}</div>{r.jamaahIds.length > r.capacity && <p className="red-text">Kapasitas kamar terlampaui</p>}{r.jamaahIds.some(id => people.find(j => j.id === id)?.gender !== r.gender) && <p className="red-text">Jenis kelamin tidak sesuai</p>}</article>)}</div><Panel title={`Belum dialokasikan (${unassigned.length})`} subtitle="Seret ke kamar atau pilih tombol Atur"><div className="panel-body">{unassigned.map(j => <div className="checklist-row" key={j.id} draggable onDragStart={e => e.dataTransfer.setData("text/plain", j.id)}><span><Person name={j.name} sub={j.gender} /></span><button className="text-button" onClick={() => setAssign(j.id)}>Atur</button></div>)}{!unassigned.length && <p className="admin-notice">Seluruh jamaah sudah mendapat kamar di {hotel}.</p>}</div></Panel></div>
    {assign && <Modal title={`Atur kamar ${people.find(j => j.id === assign)?.name}`} onClose={() => setAssign(null)}><form className="admin-form" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); if (transact(s => assignRoom(s, assign, String(f.get("room"))), "Alokasi kamar diperbarui", "Rooming")) setAssign(null); }}><label>Kamar tujuan<select name="room" required defaultValue=""><option value="" disabled>Pilih kamar</option>{rooms.map(r => <option key={r.id} value={r.id}>{r.number} · {r.gender} · {r.jamaahIds.length}/{r.capacity}</option>)}</select></label><button className="admin-button primary">Simpan alokasi</button></form></Modal>}
    {create && <Modal title="Tambah kamar" onClose={() => setCreate(false)}><form className="admin-form" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); if (transact(s => { const number = String(f.get("number")).trim(); if (s.rooms.some(r => r.departureId === departure && r.hotel === hotel && r.number === number)) throw new Error("Nomor kamar sudah digunakan."); s.rooms.push({ id: uid("ROOM"), departureId: departure, hotel, number, capacity: Number(f.get("capacity")), gender: String(f.get("gender")) as Room["gender"], jamaahIds: [] }); }, `Kamar ${hotel} ditambahkan`, "Rooming")) setCreate(false); }}><label>Nomor kamar<input name="number" required maxLength={12} /></label><label>Tipe kamar<select name="capacity"><option value="4">Quad</option><option value="3">Triple</option><option value="2">Double</option></select></label><label>Jenis kelamin<select name="gender"><option>Laki-laki</option><option>Perempuan</option></select></label><button className="admin-button primary">Tambah kamar</button></form></Modal>}
  </>;
}
